### ISSUE TITLE
Can't remove volume 

### ISSUE THREAD

**Issue by Vad1mo** [sapk/docker-volume-gluster#17]
I can't remove a volume. It says that is used by a container however this is not true, the container is removed `docker ps -a` returns an empty list. 

```
docker volume rm portainer_portainer-data 
Error response from daemon: unable to remove volume: remove portainer_portainer-data: VolumeDriver.Remove: volume portainer_portainer-data is currently used by a container
````

This is the result from the logs.
```
Dez 10 13:20:54 cluser-node-1 dockerd[15464]: time="2017-12-10T13:20:54.131124932Z" level=error msg="plugin not found"
Dez 10 13:20:55 cluser-node-1 dockerd[15464]: time="2017-12-10T13:20:55.705197900Z" level=error msg="Handler for DELETE /v1.32/volumes/portainer_portainer-data returned error: unable to remove volume: remove portainer_portainer-data: VolumeDriver.Rem...used by a container"
```

This is how I added the plugin

```
docker plugin install --grant-all-permissions --alias glusterfs sapk/plugin-gluster
```

**Comment by sapk** [comment]
I should test more the case when the plugin volume count is disconnected form docker count.
It should be possible to use force remove of volume in the meantime.

**Comment by Vad1mo** [comment]
A forced remove didn't work, what I had to do was reinstall the plugin, then the volumes where gone

**Comment by badele** [comment]
Hi,

I have a same issue.

I tried create volume with this command (use multiple servers option)
```
NODE1=$(docker inspect gluster_node-1_1 | grep '"IPAddress"' | egrep -o "[0-9+\.]+")
NODE2=$(docker inspect gluster_node-2_1 | grep '"IPAddress"' | egrep -o "[0-9+\.]+")
NODE3=$(docker inspect gluster_node-3_1 | grep '"IPAddress"' | egrep -o "[0-9+\.]+")
docker volume create --driver sapk/plugin-gluster --opt voluri="$NODE1,$NODE2,$NODE3:dockerstore" --name dockerstore
```

And use it
```
docker-recipes]$ docker run -v dockerstore:/mnt --rm -ti ubuntu
> docker: Error response from daemon: VolumeDriver.Mount: EOF
```

I try remove the volume with (steps) :
```
# Show volume
docker volume ls | grep dockerstore
> sapk/plugin-gluster:latest   dockerstore

# Try remove volume
docker volume rm dockerstore
Error response from daemon: unable to remove volume: remove dockerstore: VolumeDriver.Remove: remove /var/lib/docker-volumes/gluster/dockerstore: no such file or directory

# Try force remove volume
docker volume rm -f dockerstore
dockerstore

# Show volume
docker volume ls | grep dockerstore
> sapk/plugin-gluster:latest   dockerstore

# Try disable plugin
docker plugin disable sapk/plugin-gluster:latest

# Try Show volume (not present)
docker volume ls | grep dockerstore

# Enable plugin
docker plugin enable sapk/plugin-gluster:latest

# Show volume
docker volume ls | grep dockerstore
> sapk/plugin-gluster:latest   dockerstore
```

**Note**: I have also tried restart docker daemon

**Comment by sapk** [comment]
@badele Thx for the debug I think I may know what happen or at least find a way to not bock the removal.

**Comment by sapk** [comment]
@badele can you echo "$NODE1,$NODE2,$NODE3:dockerstore" to check the format ?

**Comment by badele** [comment]
@sapk  `docker volume create --driver sapk/plugin-gluster --opt voluri=172.19.0.4,172.19.0.3,172.19.0.2:dockerstore --name dockerstore`

**Comment by sapk** [comment]
What I can't understand is how the folder could not exist ... since it should failed at volume creation if it can't create the folder.

**Comment by badele** [comment]
Ii'm not sure, but I believe, i have that received a error during volume creation, but despite all the volume has been created.

**Comment by sapk** [comment]
The EOF error reported make me think that it would be the SaveConfig (for persistencce) that failed the volume there after disable so persistence works ...
I think, I could add a --no-persitence tag (with env also)
