### ISSUE TITLE
mount error

### ISSUE THREAD

**Issue by 694982827** [sapk/docker-volume-gluster#2]
In my gluster server:
```
[root@d71ef829f16e /]#  gluster volume info

Volume Name: gv0
Type: Replicate
Volume ID: 008f9aea-2d1b-4a1b-8c4a-ea430d84bac3
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: 10.1.139.34:/gluster/brick2
Brick2: 10.1.139.35:/gluster/brick2
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
[root@d71ef829f16e /]#
```
 and in my docker node:
`docker plugin install sapk/plugin-gluster
docker volume create --driver gluster --opt voluri="10.1.139.35:008f9aea-2d1b-4a1b-8c4a-ea430d84bac3" --name test

test
docker run -v test:/mnt --rm -ti ubuntu`
 
and it could mount when "docker run -v test:/mnt --rm -ti ubuntu

`root@osd1:~# docker run -v test:/mnt --rm -ti ubuntu

docker: Error response from daemon: VolumeDriver.Mount: exit status 1.
See 'docker run --help'.
root@osd1:~# `
`
root@docker0:~# docker plugin ls
ID                  NAME                         DESCRIPTION                   ENABLED
bed64a4a4914        sapk/plugin-gluster:latest   GlusterFS plugin for Docker   true
root@docker0:~# docker volume ls
DRIVER                       VOLUME NAME
local                        07cea292c645234f0f96293899e135450771e9056d133302197ffb58c3dc8d0a
sapk/plugin-gluster:latest   test
`

Is there anything wrong?

**Comment by sapk** [comment]
Sorry, I need to update the readme. It is not the Volume ID but Volume Name to used.

**Comment by 694982827** [comment]
@sapk 
oh ,Thanks!I have changed to the name and it work well!

**Comment by sapk** [comment]
I update the readme. Have fun ;-)
