### ISSUE TITLE
Create volume doesn't work ... ?

### ISSUE THREAD

**Issue by markhowells** [sapk/docker-volume-gluster#27]
I may be misunderstanding what happens here
I installed the plugin and ran the following

`docker volume create --driver sapk/plugin-gluster --opt voluri="cluster-server-1-data:myvol1" --name test1`

creates a volume called test1

```
# docker volume ls
DRIVER                       VOLUME NAME
sapk/plugin-gluster:latest   test1
```
However from the gluster server
```
# gluster volume status
Status of volume: gv0
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick cluster-server-1-data:/glusterstore/b
rick1/vol1                                  49152     0          Y       523  
Brick cluster-server-2-data:/glusterstore/b
rick1/vol1                                  49152     0          Y       616  
Brick cluster-server-3-data:/glusterstore/b
rick1/vol1                                  49152     0          Y       493  
Self-heal Daemon on localhost               N/A       N/A        Y       544  
Self-heal Daemon on cluster-server-3-data   N/A       N/A        Y       514  
Self-heal Daemon on cluster-server-2-data   N/A       N/A        Y       637  
 
Task Status of Volume gv0
------------------------------------------------------------------------------
There are no active volume tasks
```

where gv0 is a pre-existing volume. I expected to see a new volume ?

Of course, attempting to run a container with the mounted volume causes an error

Creating a docker volume against gv0 works as expected and mounts successfully. 

Am I misunderstanding something or is there an error somewhere?

Also, I set DEBUG=1 but can't work out how to view the logging (I'm not familiar with goloang)

**Comment by sapk** [comment]
You need to create the gluster volume before via gluster cli. 
docker create a volume to use the gluster volume but those are two different volume definition.
I plan to add the func to create the gluster volume automatically from the docker volume definition but this is problematic since gluster can create various type of volume.

**Comment by sapk** [comment]
As for DEBUG env it is not yet implemented in the container on docker hub. it's right now in the oven and should be released soon. And debug docker plugin is "hard" since they are container but hidden from docker ps list ^^

**Comment by markhowells** [comment]
I did wonder about the multiple gluster volume types - this is a great plugin, I'll keep testing it.

**Comment by sapk** [comment]
I will close this one since there is already #5
