### ISSUE TITLE
Feature: creation of sub directory into glusterfs volume

### ISSUE THREAD

**Issue by kladiv** [sapk/docker-volume-gluster#35]
@sapk 
Is it ppssible add a feature (e.g. additional parameter of volume create) to allow creation of sub-directory into GlusterFS volume so we can use 1 volume for multiple containers (lots of sub folders)?
 
It should be better then create lots of volumes (per-container) on dense environments.

Gluster cli already allow managing of directory quotas even if folders are not yet created.

**Comment by sapk** [comment]
That shouldn't be too hard to do. It maybe possible to add the subdir inside voluri and keep backward compat.

**Comment by trajano** [comment]
You need to have GlusterFS 3.12 at minimum for this to work.  I think you may be using an older version of GlusterFS which is causing it to fail on my set up.

**Comment by sapk** [comment]
@trajano this is not implemented yet. I was just talking about a way to implement it.

**Comment by trajano** [comment]
I think if you just use Gluster 3.12 or assume Gluster 3.12 is installed (I don't think you make any assumption on what is installed though because I see the volume mounted even without the glusterfs client installed by yum) then you can simply pass in

`store:/myvol/subvol`

**Comment by sapk** [comment]
In managed plugin, glusterfs should be 3.13 https://packages.debian.org/fr/testing/glusterfs-client.

But, I use the glusterfs command and not mount (https://packages.debian.org/fr/testing/glusterfs-client). This allow for multiple server as base and I don't know if it support that "new" format. In the docs (https://docs.gluster.org/en/latest/release-notes/3.12.0/), they only with mount command.

**Comment by trajano** [comment]
The parseVolUri needs to add `--subdir-mount=SUBDIR-PATH`

**Comment by trajano** [comment]
I tried to make it but I don't know Go well enough here's my cut
```
const (
	validHostnameRegex = `(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])`
	validMountRegex = `\/?([^\/]+)(/[^\/]+)?`
)

func isValidURI(volURI string) bool {
	re := regexp.MustCompile(validHostnameRegex + ":" + validMountRegex)
	return re.MatchString(volURI)
}

func parseVolURI(volURI string) string {
	volParts := strings.Split(volURI, ":")
	volServers := strings.Split(volParts[0], ",")

	re := regexp.MustCompile(validMountRegex)
	??? := re.MatchString(volParts[1])
	volumeIdPart := ???.group(1)
	subDirectoryPart := ???.group(2)
	
	if (subDirectoryPart == nil) {
		return fmt.Sprintf("--volfile-id='%s' -s '%s'", volumeIdPart, strings.Join(volServers, "' -s '"))
	} else {
		return fmt.Sprintf("--volfile-id='%s' --subdir-mount='%s' -s '%s'", volumeIdPart, subDirectoryPart, strings.Join(volServers, "' -s '"))

	}
}


```

**Comment by sapk** [comment]
I will have a look at it tommorrow.
If you want to contribute you can submit a PR with tests that should validate the change. https://github.com/sapk/docker-volume-gluster/blob/master/gluster/driver/tools_test.go 
This would be a easy start at go. It is mostly adding new case to check to the two first functions.

**Comment by kladiv** [comment]
Great job guys :)

**Comment by sapk** [comment]
Doing more tests but should release soon.

**Comment by moetemad** [comment]
@sapk Has this feature made it into any of the releases yet? I am still having issues with gluster 5.3
