### ISSUE TITLE
I am unable to remove the volume even with -f

### ISSUE THREAD

**Issue by trajano** [sapk/docker-volume-gluster#39]
- Plugin version (or commit ref) :latest
- Docker version :18.03
- Plugin type : managed
- Operating system:

## Description

I am unable to remove a volume even with the `-f`

## Logs

Here is what happens
```
trajano@noriko MINGW64 /d/p/trajano.net/jenkins (master)
$ docker volume rm -f test
test

trajano@noriko MINGW64 /d/p/trajano.net/jenkins (master)
$ docker volume ls
DRIVER                       VOLUME NAME
local                        722a2fa4d4e0d5bff53257b822e0eb175d092b1270c90b8b6c00215a5a1dcce1
local                        957185ba07393749e458f79bc6cada77f6447b1cabed1993ce95a8e877e984b5
local                        ddf5beffd17c3ed35dc4d2bfae51d0ef2c89ddfdd009890b73e8ada21827042b
sapk/plugin-gluster:latest   jenkins_jenkins_home
sapk/plugin-gluster:latest   jenkins_nexus-data
sapk/plugin-gluster:latest   test

```

**Comment by sapk** [comment]
@trajano What error do you get when doing `docker volume rm test` ?

**Comment by trajano** [comment]
No error, it just says "test" or whatever I put in.  The closest thing I can do to remove it is to actualy disable the plugin.

**Comment by sapk** [comment]
Ok so it must unmount it but not remove it from the information that the plugin keep of volumes. It must come from recent refactor to have a common base for the multiple volume driver. I will have a look at it.

**Comment by trajano** [comment]
works thanks now just need that #35 :)
