### ISSUE TITLE
raspberry pi build

### ISSUE THREAD

**Issue by lukicsl** [sapk/docker-volume-gluster#55]
I am trying to create the pluging for raspbery pi (armv7l).

when running make on the cloned reposity I get following error:
`# github.com/sapk/docker-volume-gluster/gluster/driver`
 `gluster/driver/tools.go:79: undefined: url.PathEscape`
`gluster/driver/tools.go:81: undefined: url.PathEscape`
`Makefile:77: recipe for target 'compile' failed`
`make: *** [compile] Error 2`
I looking for a solution for a manage gluster fs plugin on raspberry pi

**Comment by sapk** [comment]
What version of go do you use ? If I remember url.PathEscape was introduce on go 1.8.

**Comment by lukicsl** [comment]
go version go1.7.4 linux/arm

**Comment by lukicsl** [comment]
Updated go to 
go version go1.9 linux/arm
works now

**Comment by lukicsl** [comment]
How do I install the compiled driver?
in order to
`docker plugin install sapk/plugin-gluster`

**Comment by sapk** [comment]
@lukicsl Perfect, I should add the minimum version needed to the Reame.

**Comment by lukicsl** [comment]
The installtion to local repo?

**Comment by sapk** [comment]
I think you may have confused the two way to use docker plugin (managed vs legacy). What command did you use to compile ?

**Comment by lukicsl** [comment]
Just
make

I am a newbi regarding plugins

**Comment by sapk** [comment]
No problem for the confusion, the docker docs doesn't help on this subject and it is quite confusing. Basically, managed plugin are legacy plugin inside a container that can be distributed as an image via registry. 
To build the managed plugin use: `make docker-plugin` (https://github.com/sapk/docker-volume-gluster/blob/old/Makefile#L42)
This will build the image. 
You can enable it with `make docker-plugin-enable` (https://github.com/sapk/docker-volume-gluster/blob/old/Makefile#L68)

If you want to publish the result to a registry you can set custom env variable 
```
PLUGIN_USER ?= sapk
PLUGIN_NAME ?= plugin-gluster
PLUGIN_TAG ?= latest
```
and use the command ```docker-plugin-push``` to publish to docker hub.

Ex: 
```
#To build lukicsl/plugin-gluster:armv7l
PLUGIN_USER=lukicsl PLUGIN_TAG=armv7l make docker-plugin
#To test lukicsl/plugin-gluster:armv7l
PLUGIN_USER=lukicsl PLUGIN_TAG=armv7l make docker-plugin-enable
#To publish to docker hub lukicsl/plugin-gluster:armv7l
PLUGIN_USER=lukicsl PLUGIN_TAG=armv7l make docker-plugin-push
```

Please let me know if it works (normally it should but I never try). 
I could try to setup multi-arch plugin like I have done for some of my other docker images.

**Comment by lukicsl** [comment]
Great!
I will try it today.
Thanks

**Comment by lukicsl** [comment]
Works perfect
